name: Publish to PyPI

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine wheel
    
    - name: Validate version
      run: |
        # Extract tag version (remove 'v' prefix)
        TAG_VERSION=${GITHUB_REF#refs/tags/v}
        echo "Tag version: $TAG_VERSION"
        
        # Get version from setup.py
        SETUP_VERSION=$(python -c "from setuptools import setup; import sys; sys.argv=['setup.py', '--version']; exec(open('setup.py').read())")
        echo "Setup.py version: $SETUP_VERSION"
        
        # Compare versions
        if [ "$TAG_VERSION" != "$SETUP_VERSION" ]; then
          echo "Error: Tag version ($TAG_VERSION) does not match setup.py version ($SETUP_VERSION)"
          exit 1
        fi
        echo "Version validation successful!"
    
    - name: Run tests
      run: |
        pip install -e .[dev]
        pytest tests/
    
    - name: Build package
      run: |
        python -m build
    
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        password: ${{ secrets.PYPI_API_TOKEN }} 