name: Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, '3.10', '3.11']

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        python -m pip install pytest pytest-cov black
        if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
        
    - name: Check formatting with Black
      run: |
        black --check --diff suggest tests
        
    - name: Run unit tests
      run: |
        python -m unittest discover
        
    - name: Run coverage
      run: |
        pytest --cov=suggest tests/
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        fail_ci_if_error: false 